/**
 * OpenAPI Schema for Salesforce Functions invocation contexts
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
* Extra response out-of-band information returned from function invocation
*/
export class ResponseExtraInfo {
    /**
    * Unique function request identifier
    */
    'requestId': string;
    /**
    * Resource identifier of function being invoked
    */
    'resource'?: string;
    /**
    * Source path:line number if possible to fill in on error, null/undefined otherwise
    */
    'source'?: string;
    /**
    * Execution time in milliseconds, may include fractional millis after decimal point
    */
    'execTimeMs'?: number;
    /**
    * HTTP status code of response: 200-599, -1 if non-HTTP error encountered.
    */
    'statusCode'?: number;
    /**
    * Flag set to true if error encountered in function code, false if other error, null/undefined if no error
    */
    'isFunctionError'?: boolean;
    /**
    * Language-specific error stack trace to help developer diagnose issues, null/undefined if no error
    */
    'stack'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "requestId",
            "baseName": "requestId",
            "type": "string"
        },
        {
            "name": "resource",
            "baseName": "resource",
            "type": "string"
        },
        {
            "name": "source",
            "baseName": "source",
            "type": "string"
        },
        {
            "name": "execTimeMs",
            "baseName": "execTimeMs",
            "type": "number"
        },
        {
            "name": "statusCode",
            "baseName": "statusCode",
            "type": "number"
        },
        {
            "name": "isFunctionError",
            "baseName": "isFunctionError",
            "type": "boolean"
        },
        {
            "name": "stack",
            "baseName": "stack",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ResponseExtraInfo.attributeTypeMap;
    }
}

