/**
 * OpenAPI Schema for Salesforce Functions invocation contexts
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { UserContext } from './userContext';

/**
* Salesforce context information
*/
export class SfContext {
    /**
    * Salesforce API Version in form like: 53.0
    */
    'apiVersion': string;
    /**
    * Payload version indicating JSON-format
    */
    'payloadVersion': string;
    'userContext': UserContext;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "apiVersion",
            "baseName": "apiVersion",
            "type": "string"
        },
        {
            "name": "payloadVersion",
            "baseName": "payloadVersion",
            "type": "string"
        },
        {
            "name": "userContext",
            "baseName": "userContext",
            "type": "UserContext"
        }    ];

    static getAttributeTypeMap() {
        return SfContext.attributeTypeMap;
    }
}

