/**
 * Copyright (c) 2022, salesforce.com, inc.
 * All rights reserved.
 * SPDX-License-Identifier: BSD-3-Clause
 * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { UserContext } from './userContext';

/**
* Salesforce context information
*/
export class SfContext {
    /**
    * Salesforce API Version in form like: 53.0
    */
    'apiVersion': string;
    /**
    * Payload version indicating JSON-format
    */
    'payloadVersion': string;
    'userContext': UserContext;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "apiVersion",
            "baseName": "apiVersion",
            "type": "string"
        },
        {
            "name": "payloadVersion",
            "baseName": "payloadVersion",
            "type": "string"
        },
        {
            "name": "userContext",
            "baseName": "userContext",
            "type": "UserContext"
        }    ];

    static getAttributeTypeMap() {
        return SfContext.attributeTypeMap;
    }
}

