/**
 * Copyright (c) 2022, salesforce.com, inc.
 * All rights reserved.
 * SPDX-License-Identifier: BSD-3-Clause
 * For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
* Salesforce Function invocation context information
*/
export class SfFnContext {
    /**
    * In-band access token to use for local Functions testing, not populated in production calls
    */
    'accessToken'?: string;
    /**
    * Unique function invocation identifier, only populated for async function invocations
    */
    'functionInvocationId'?: string;
    /**
    * (internal use only)
    */
    'proxyClientToken'?: string;
    /**
    * Qualified function name in the form <project>.<fnname> or <namespace>.<project>.<fnname>
    */
    'functionName': string;
    /**
    * Unique Apex class identifier that invoked this function
    */
    'apexId'?: string;
    /**
    * Apex qualified name that invoked this function in the form Pathname/filename.cls:linenum
    */
    'apexFQN'?: string;
    /**
    * Unique function request identifier
    */
    'requestId': string;
    /**
    * Resource identifier of function being invoked
    */
    'resource'?: string;
    /**
    * (internal use only)
    */
    'asyncResponseCallbackPath'?: string;
    /**
    * Deadline datetime (UTC) prior to which the Function request must complete: yyyy-MM-dd\'T\'HH:mm:ssZ
    */
    'deadline'?: Date;
    /**
    * Optional Namespace prefix for the functions
    */
    'functionNamespace'?: string;
    /**
    * Optional Namespace prefix for the invoking apex code
    */
    'invokingNamespace'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "accessToken",
            "baseName": "accessToken",
            "type": "string"
        },
        {
            "name": "functionInvocationId",
            "baseName": "functionInvocationId",
            "type": "string"
        },
        {
            "name": "proxyClientToken",
            "baseName": "proxyClientToken",
            "type": "string"
        },
        {
            "name": "functionName",
            "baseName": "functionName",
            "type": "string"
        },
        {
            "name": "apexId",
            "baseName": "apexId",
            "type": "string"
        },
        {
            "name": "apexFQN",
            "baseName": "apexFQN",
            "type": "string"
        },
        {
            "name": "requestId",
            "baseName": "requestId",
            "type": "string"
        },
        {
            "name": "resource",
            "baseName": "resource",
            "type": "string"
        },
        {
            "name": "asyncResponseCallbackPath",
            "baseName": "asyncResponseCallbackPath",
            "type": "string"
        },
        {
            "name": "deadline",
            "baseName": "deadline",
            "type": "Date"
        },
        {
            "name": "functionNamespace",
            "baseName": "functionNamespace",
            "type": "string"
        },
        {
            "name": "invokingNamespace",
            "baseName": "invokingNamespace",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return SfFnContext.attributeTypeMap;
    }
}

