/**
 * OpenAPI Schema for Salesforce Functions invocation contexts
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
* Salesforce user/org context information
*/
export class UserContext {
    /**
    * 18-character unique Org identifier
    */
    'orgId': string;
    /**
    * 18-character unique User identifier
    */
    'userId': string;
    /**
    * Optional 18-character unique User identifier invoked-on-behalf-of
    */
    'onBehalfOfUserId'?: string;
    /**
    * Unique username
    */
    'username': string;
    /**
    * Base URL of Salesforce appserver that invoked function
    */
    'salesforceBaseUrl': string;
    /**
    * MyDomain URL of Salesforce appserver that invoked function
    */
    'orgDomainUrl'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "orgId",
            "baseName": "orgId",
            "type": "string"
        },
        {
            "name": "userId",
            "baseName": "userId",
            "type": "string"
        },
        {
            "name": "onBehalfOfUserId",
            "baseName": "onBehalfOfUserId",
            "type": "string"
        },
        {
            "name": "username",
            "baseName": "username",
            "type": "string"
        },
        {
            "name": "salesforceBaseUrl",
            "baseName": "salesforceBaseUrl",
            "type": "string"
        },
        {
            "name": "orgDomainUrl",
            "baseName": "orgDomainUrl",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return UserContext.attributeTypeMap;
    }
}

